exports.s_pPathGrossini       = "Images/grossini.png"
exports.s_pPathSister1        = "Images/grossinis_sister1.png"
exports.s_pPathSister2        = "Images/grossinis_sister2.png"
exports.s_pPathB1             = "Images/b1.png"
exports.s_pPathB2             = "Images/b2.png"
exports.s_pPathR1             = "Images/r1.png"
exports.s_pPathR2             = "Images/r2.png"
exports.s_pPathF1             = "Images/f1.png"
exports.s_pPathF2             = "Images/f2.png"
exports.s_pPathBlock          = "Images/blocks.png"
exports.s_back                = "Images/background.png"
exports.s_back1               = "Images/background1.png"
exports.s_back2               = "Images/background2.png"
exports.s_back3               = "Images/background3.png"
exports.s_stars1              = "Images/stars.png"
exports.s_stars2              = "Images/stars2.png"
exports.s_fire                = "Images/fire.png"
exports.s_snow                = "Images/snow.png"
exports.s_streak              = "Images/streak.png"
exports.s_PlayNormal          = "Images/btn-play-normal.png"
exports.s_PlaySelect          = "Images/btn-play-selected.png"
exports.s_AboutNormal         = "Images/btn-about-normal.png"
exports.s_AboutSelect         = "Images/btn-about-selected.png"
exports.s_HighNormal          = "Images/btn-highscores-normal.png"
exports.s_HighSelect          = "Images/btn-highscores-selected.png"
exports.s_Ball                = "Images/ball.png"
exports.s_Paddle              = "Images/paddle.png"
exports.s_pPathClose          = "Images/close.png"
exports.s_MenuItem            = "Images/menuitemsprite.png"
exports.s_SendScore           = "Images/SendScoreButton.png"
exports.s_PressSendScore      = "Images/SendScoreButtonPressed.png"
exports.s_Power               = "Images/powered.png"
exports.s_AtlasTest           = "Images/atlastest.png"

// tilemaps resource
exports.s_TilesPng            = "TileMaps/tiles.png"
exports.s_LevelMapTga         = "TileMaps/levelmap.tga"

// spine test resource
exports.s_pPathSpineBoyJson       = "spine/spineboy.json"
exports.s_pPathSpineBoyAtlas       = "spine/spineboy.atlas"

// fonts resource
exports.s_markerFeltFontPath   = "fonts/Marker Felt.ttf"
exports.s_arialPath            = "fonts/arial.ttf"
exports.s_thonburiPath         = "fonts/Thonburi.ttf"
exports.s_tahomaPath           = "fonts/tahoma.ttf"

exports.s_s9s_ui_plist         = "Images/ui.plist"
